### ISSUE TITLE
Java 17 not supported due to jdk8 docker image used

### ISSUE THREAD

**Issue by costea32** [sonatype-nexus-community/circleci-maven-release-orb#6]
Hello, I'm trying to release a project built with java 17 but the docker image used by the orb is cimg/openjdk:8.0 
can this be upgraded to a higher version or at least provided options for choosing which image to use?

**Comment by bhamail** [comment]
I haven't tried this myself, but perhaps you can override the default `executor` by setting your own `executor`?

**Comment by costea32** [comment]
indeed, it was not very clear initially how to do this but in the end here is the example that worked:
```
version: 2.1
orbs:
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@0.0.16

executors:
  openjdk17:
    docker:
      - image: cimg/openjdk:17.0

workflows:
  version: 2.1
  
  release:
    jobs:
      - test
      - circleci-maven-release-orb/run-maven-release:
          requires:
            - test
          ssh-fingerprints: '<fingerprint here>'
          executor: openjdk17
```
